import { TriggerType } from "../item-core";
import { pathToArr, deepGet, deepSet } from "./object";
export { pathToArr, deepGet, deepSet };
export declare function isExitPrefix(prefix: string, path: string | string[]): boolean;
export declare function getValuePropName(valueProp: string | ((type: any) => string), type: any): string;
export declare function getValueFromEvent(...args: any[]): any;
export declare const isWithBracket: (part?: any) => boolean;
export declare const isValidNumber: (item?: any) => true | undefined;
export declare function joinFormPath(...args: Array<any>): any;
export declare const validateTriggerCondition: (eventName?: TriggerType | boolean, validateTrigger?: TriggerType | TriggerType[]) => boolean | undefined;
export declare function toArray<T>(list: T | T[]): T[];
